// Migration for table: gruposdsm
exports.up = function(knex) {
  return knex.schema.createTable('gruposdsm', table => {
    table.increments('cd_grupodsm'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('ds_grupodsm', 250).notNullable();
    table.integer('cd_grupodsmpai').nullable().references('cd_grupodsm').inTable('gruposdsm'); // Recursive foreign key to the same table
    table.integer('versao').nullable().check('versao IN (4, 5)'); // Check for DSM-IV (4) or DSM-5 (5)
    table.primary(['cd_grupodsm']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('gruposdsm');
};