// Migration for table: unidadesorganizacionais
exports.up = function(knex) {
  return knex.schema.createTable('unidadesorganizacionais', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNull();
    table.integer('cd_unidadepai').references('codigo').inTable('unidadesorganizacionais'); // Optional foreign key for hierarchical structure
    table.string('tipo', 20).notNull();
    table.boolean('ativo').defaultTo(true).notNull(); // Assumes active status by default
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('unidadesorganizacionais');
};