// Migration for table: cidades
exports.up = function(knex) {
  return knex.schema.createTable('cidades', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNull();
    table.char('cdUf', 2).notNull().references('codigo').inTable('unidadesfederacao'); // Foreign key reference to unidadesfederacao
    table.integer('cdPais').notNull().references('codigo').inTable('paises'); // Foreign key reference to paises
    table.string('cepGeral', 9).notNull();
    table.integer('cdIbge'); // Optional IBGE code
    table.string('stInativo', 1).defaultTo('N');
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('cidades');
};