// Migration for table: cidades
exports.up = function(knex) {
  return knex.schema.createTable('cidades', function(table) {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNullable();
    table.char('cdUf', 2).notNullable().references('codigo').inTable('unidadesfederacao'); // Foreign key reference to unidadesfederacao
    table.integer('cdPais').notNullable().references('codigo').inTable('paises'); // Foreign key reference to paises
    table.string('cepGeral', 9).notNullable();
    table.integer('cdIbge').nullable(); // Optional IBGE code
    table.string('stInativo', 1).defaultTo('N').nullable();
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('cidades');
};