// Migration for table: agendaprofissionais
exports.up = function(knex) {
  return knex.schema.createTable('agendaprofissionais', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigoprofissional').notNullable().references('codigoprof').inTable('profissionais'); // Foreign key to profissionais table
    table.timestamp('datahorainicio').notNullable();
    table.timestamp('datahorafim').notNullable();
    table.integer('codigounidade').notNullable().references('codigo').inTable('unidadesorganizacionais'); // Foreign key to unidadesorganizacionais table
    table.string('tipo', 20).notNullable(); // Could specify the type of appointment or session
    table.text('descricao').nullable(); // Optional detailed description of the appointment
    table.boolean('ativo').defaultTo(true).notNullable(); // Whether the schedule is active
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('agendaprofissionais');
};
