// Migration for table: contasreceber
exports.up = function(knex) {
  return knex.schema.createTable('contasreceber', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigocliente').notNull().references('codigo').inTable('clientes'); // Foreign key to clientes table
    table.decimal('valor', 14, 2).notNull(); // Monetary value of the account receivable
    table.date('datavencimento').notNull(); // Due date for the receivable
    table.date('datapagamento'); // Date when payment was made
    table.boolean('pago').defaultTo(false).notNull(); // Whether the amount has been paid
    table.text('descricao'); // Optional description of the receivable
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('contasreceber');
};
