// Migration for table: agendaprofissionais
exports.up = function(knex) {
  return knex.schema.createTable('agendaprofissionais', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigoprofissional').notNull().references('codigoprof').inTable('profissionais'); // Foreign key to profissionais table
    table.timestamp('datahorainicio').notNull();
    table.timestamp('datahorafim').notNull();
    table.integer('codigounidade').notNull().references('codigo').inTable('unidadesorganizacionais'); // Foreign key to unidadesorganizacionais table
    table.string('tipo', 20).notNull(); // Could specify the type of appointment or session
    table.text('descricao'); // Optional detailed description of the appointment
    table.boolean('ativo').defaultTo(true).notNull(); // Whether the schedule is active
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('agendaprofissionais');
};
