// Migration for table: quadrosvagas
exports.up = function(knex) {
  return knex.schema.createTable('quadrosvagas', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNull();
    table.integer('totalvagas').notNull();
    table.integer('vagasocupadas').notNull();
    table.integer('vagasdisponiveis').notNull();
    table.string('local', 100);
    table.timestamp('dataultimaatualizacao').defaultTo(knex.fn.now());
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('quadrosvagas');
};