// Migration for table: unidadesorganizacionais
exports.up = function(knex) {
  return knex.schema.createTable('unidadesorganizacionais', function(table) {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNullable();
    table.integer('cd_unidadepai').nullable().references('codigo').inTable('unidadesorganizacionais'); // Optional foreign key for hierarchical structure
    table.string('tipo', 20).notNullable();
    table.boolean('ativo').defaultTo(true).notNullable(); // Assumes active status by default
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('unidadesorganizacionais');
};