// Migration for table: profissionais
exports.up = function(knex) {
  return knex.schema.createTable('profissionais', table => {
    table.increments('codigoprof'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('nome', 50).notNull();
    table.string('sexo', 1).notNull().check('sexo IN (\'M\', \'F\', \'I\')'); // M for Male, F for Female, I for Intersex/Other
    table.date('dtnascimento').notNull();
    table.string('cpf', 11).notNull().unique();
    table.string('rg', 15);
    table.string('orgaoemissor', 10);
    table.integer('codigocargo').references('codigo').inTable('cargos'); // Optional foreign key to cargos
    table.string('cd_situacao', 1); // Could have a check constraint if specific codes are known
    table.timestamp('dt_admissao');
    table.timestamp('dt_demissao');
    table.string('apelido', 20);
    table.string('entidadeclasse', 100);
    table.string('conselhoprofissional', 7);
    table.string('email', 200).notNull().unique();
    table.string('nmCivil', 50);
    table.string('stNmSocial', 1).defaultTo('N').check('stNmSocial IN (\'S\', \'N\')'); // S for Social Name, N for not used
    table.primary(['codigoprof']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('profissionais');
};