// Migration for table: planos
exports.up = function(knex) {
  return knex.schema.createTable('planos', function(table) {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNullable();
    table.decimal('valor', 14, 2).notNullable(); // Assuming a decimal type for money values
    table.integer('qtd_profissinais').notNullable();
    table.integer('qtd_clinicas').notNullable();
    table.timestamp('validade_inicio').notNullable();
    table.timestamp('validade_final').nullable();
    table.string('st_inativo', 1).defaultTo('N').check('st_inativo IN (\'S\', \'N\')'); // Adds a check constraint
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('planos');
};