// Migration for table: motivosexclamacao
exports.up = function(knex) {
  return knex.schema.createTable('motivosexclamacao', function(table) {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNullable();
    table.string('stinativo', 1).defaultTo('N').notNullable(); // Defaults to 'N' and is not nullable
    table.check('stinativo IN (\'S\', \'N\')'); // Adding the check constraint for 'S' or 'N'
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('motivosexclamacao');
};