// Migration for table: ocupacoes
exports.up = function(knex) {
  return knex.schema.createTable('ocupacoes', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 250).notNull();
    table.string('ocupacao', 10); // Optionally store an occupation code or similar identifier
    table.integer('cd_ocupacaopai'); // Optional reference to a parent occupation
    table.string('stInativo', 1).defaultTo('N'); // Status inactive, defaults to 'N'
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('ocupacoes');
};