// Migration for table: dsm_master
exports.up = function(knex) {
  return knex.schema.createTable('dsm_master', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 255).notNull();
    table.string('codigo_dsm', 10).notNull().unique(); // Unique DSM code
    table.integer('cd_grupodsm').references('cd_grupodsm').inTable('gruposdsm'); // Optional foreign key to gruposdsm
    table.boolean('ativo').defaultTo(true).notNull(); // Whether the DSM entry is active
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('dsm_master');
};