// Migration for table: tiposprocedimentos
exports.up = function(knex) {
  return knex.schema.createTable('tiposprocedimentos', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNull();
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('tiposprocedimentos');
};