// Migration for table: quadrosvagas
exports.up = function(knex) {
  return knex.schema.createTable('quadrosvagas', function(table) {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNullable();
    table.integer('totalvagas').notNullable();
    table.integer('vagasocupadas').notNullable();
    table.integer('vagasdisponiveis').notNullable();
    table.string('local', 100).nullable();
    table.timestamp('dataultimaatualizacao').defaultTo(knex.fn.now());
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('quadrosvagas');
};