// Migration for table: contasreceber
exports.up = function(knex) {
  return knex.schema.createTable('contasreceber', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigocliente').notNullable().references('codigo').inTable('clientes'); // Foreign key to clientes table
    table.decimal('valor', 14, 2).notNullable(); // Monetary value of the account receivable
    table.date('datavencimento').notNullable(); // Due date for the receivable
    table.date('datapagamento').nullable(); // Date when payment was made
    table.boolean('pago').defaultTo(false).notNullable(); // Whether the amount has been paid
    table.text('descricao').nullable(); // Optional description of the receivable
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('contasreceber');
};
