// Migration for table: escolaridades
exports.up = function(knex) {
  return knex.schema.createTable('escolaridades', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNull();
    table.string('stinativo', 1).defaultTo('N').notNull(); // Assuming it should be notNullable based on the use of default and check constraint in SQL
    table.check('stinativo IN (\'S\', \'N\')'); // Adding the check constraint
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('escolaridades');
};