// Migration for table: enderecos
exports.up = function(knex) {
  return knex.schema.createTable('enderecos', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.string('enderecoresidencia', 125);
    table.string('nr_residencia', 10);
    table.string('complementoresidencia', 100);
    table.string('bairroresidencia', 100);
    table.string('cep_residencia', 10);
    table.integer('cdCidadeResidencia').notNull().references('codigo').inTable('cidades'); // Foreign key reference to cidades
    table.timestamp('dtAtualizacao').defaultTo(knex.fn.now());
    table.string('telefone', 10).notNull();
    table.char('tp_pessoalcontato', 1);
    table.integer('ddd');
    table.string('nm_contato', 100);
    table.char('tp_fone', 1).check('tp_fone IN (\'R\', \'T\', \'C\', \'P\')'); // Check constraint for phone type
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('enderecos');
};
