// Migration for table: assinaturas
exports.up = function(knex) {
  return knex.schema.createTable('assinaturas', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigomaster').notNull().references('codigo').inTable('master'); // Foreign key to master table
    table.integer('codigoprofissional').notNull().references('codigoprof').inTable('profissionais'); // Foreign key to profissionais table
    table.integer('codigoarquivo').notNull(); // Assuming it references an 'arquivos' table
    table.timestamp('dataassinatura').defaultTo(knex.fn.now()); // Timestamp of when the signature was applied
    table.boolean('ativo').defaultTo(true).notNull(); // Whether the signature is active
    table.string('hashassinatura', 255).notNull(); // Store the hash of the signature for verification purposes
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('assinaturas');
};