// Migration for table: paises
exports.up = function(knex) {
  return knex.schema.createTable('paises', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 35).notNull();
    table.string('nacionalidade', 50);
    table.integer('cdIbge'); // Optional integer field for additional identifiers like IBGE codes
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('paises');
};
