// Migration for table: planos
exports.up = function(knex) {
  return knex.schema.createTable('planos', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNullable();
    table.decimal('valor', 14, 2).notNullable(); // Assuming a decimal type for money values
    table.integer('qtd_profissinais').notNullable();
    table.integer('qtd_clinicas').notNullable();
    table.timestamp('validade_inicio').notNullable();
    table.timestamp('validade_final').nullable();
    table.string('st_inativo', 1).defaultTo('N'); // Adds a check constraint
    table.primary(['codigo']); // Sets the primary key
  }).then(() => knex.raw("ALTER TABLE planos ADD CONSTRAINT st_inativo_check CHECK (st_inativo IN ('S', 'N'))"));
};

exports.down = function(knex) {
  return knex.schema.dropTable('planos');
};


