// Migration for table: master
exports.up = function(knex) {
  return knex.schema.createTable('master', table => {
    table.increments('codigo'); // Handles the int4 GENERATED BY DEFAULT AS IDENTITY
    table.integer('codigomaster').notNull().references('codigo').inTable('master'); // Self-referencing foreign key for hierarchical relationships
    table.string('nome', 50).notNull();
    table.string('email', 200).notNull().unique();
    table.timestamp('dt_atualizacao').defaultTo(knex.fn.now());
    table.string('password', 255).notNull();
    table.boolean('admin').defaultTo(false).notNull();
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('master');
};
