// Migration for table: locaisatendimentos
exports.up = function(knex) {
  return knex.schema.createTable('locaisatendimentos', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 100).notNullable();
    table.string('siglaUnidade', 10).nullable();
    table.string('endereco', 150).nullable();
    table.string('telefone', 50).nullable();
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('locaisatendimentos');
};