// Migration for table: cargos
exports.up = function(knex) {
  return knex.schema.createTable('cargos', table => {
    table.increments('codigo'); // Handles the int2 GENERATED BY DEFAULT AS IDENTITY
    table.string('descricao', 50).notNull();
    table.integer('cdNivel');
    table.string('stInativo', 1).defaultTo('N');
    table.primary(['codigo']); // Sets the primary key
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('cargos');
};
